/*

 JOINS

 1 ) INNER JOIN
 2 ) OUTER JOIN / FULL OUTER JOIN 
	 i ) LEFT JOIN / LEFT OUTER JOIN
	 ii ) RIGHT JOIN / RIGHT OUTER JOIN

 */

 -- i ) INNER JOIN

 SELECT * FROM product
 INNER JOIN 
 SELECT * FROM SHOP
 --Incorrect syntax near the keyword 'SELECT'

 SELECT * FROM 
 product
 INNER JOIN 
 SHOP
 ON product.cust_id = SHOP.ID
 WHERE 
 product.prod_quantity > 9

 --------------------------------

 SELECT P.ID,P.PROD_ID,P.PROD_NAME,P.prod_quantity,P.CUST_ID,S.CUST_NAME,S.cust_prod,S.cust_amt FROM 
 product P
 INNER JOIN 
 SHOP S
 ON P.cust_id = S.ID
 WHERE 
 P.prod_quantity > 9

 -- 2 ) FULL OUTER JOIN
 
 SELECT P.ID,P.PROD_ID,P.PROD_NAME,P.prod_quantity,P.CUST_ID,S.CUST_NAME,S.cust_prod,S.cust_amt FROM 
 product P
 FULL OUTER JOIN 
 SHOP S
 ON P.cust_id = S.ID
 --WHERE 
 --P.prod_quantity > 1

 -- 3 ) LEFT JOIN / LEFT OUTER JOIN 

 SELECT P.ID,P.PROD_ID,P.PROD_NAME,P.prod_quantity,P.CUST_ID FROM 
 product P
 LEFT OUTER JOIN 
 SHOP S
 ON P.cust_id = S.ID

 ----
 
 SELECT P.ID,P.PROD_ID,P.PROD_NAME,P.prod_quantity,P.CUST_ID FROM 
 product P
 LEFT JOIN 
 SHOP S
 ON P.cust_id = S.ID

 -- 4 ) RIGHT JOIN / RIGHT OUTER JOIN

 SELECT P.id, S.CUST_NAME,S.CUST_PROD,S.CUST_AMT FROM product P RIGHT JOIN SHOP S
 ON P.CUST_ID = S.id

 ----
 
 SELECT P.id, S.CUST_NAME,S.CUST_PROD,S.CUST_AMT FROM product P RIGHT OUTER JOIN SHOP S
 ON P.CUST_ID = S.id

 SELECT P.id, S.CUST_NAME,S.CUST_PROD,S.CUST_AMT FROM product P RIGHT OUTER JOIN SHOP S
 ON P.CUST_ID = S.id
 WHERE
 S.cust_amt >= 30000

 -- 5 ) SELF JOIN (,)

 SELECT * FROM SHOP S1 , SHOP S2

 -- HOW MANY CUSTOMER RELIGION ARE IN INDIAN WITH COUNTRY INDIA
 -- Ambiguous column name 'COUNTRY'.
 SELECT C1.SNO,C1.NAME,C1.AGE,C1.COUNTRY,C1.RELIGION,C1.SALARY FROM CUSTOMERS C1 , CUSTOMERS C2
 WHERE
 C1.SNO <> C2.SNO
 AND 
 C1.RELIGION = C1.RELIGION
 ORDER BY SNO

 -- 6 ) CROSS JOIN (CARTITION / PRODUCT)

SELECT P.cust_id,P.prod_id,P.prod_name,P.prod_quantity
FROM PRODUCT P
CROSS JOIN SHOP S;

-------------------------------------------------

-- CASE

--SWITCH CASE

--CASE (COL_NAME) // OPTIONAL
--	WHEN (CONDITION) 
--	 QUERY'TRUE'
--	 THEN
--	 QUERY 'FALSE'
--END

SELECT * FROM product
WHERE
prod_name = 'Books'

SELECT * , 
(CASE 
	WHEN salary < 10000 THEN 'Low'
    WHEN salary >= 10000 AND salary <= 30000 THEN 'Average'
    WHEN salary > 50000 THEN 'High'	 
END) C_N 
FROM CUSTOMERS
--------------------
SELECT * , 
(CASE 
	WHEN (PROD_NAME = 'Laptop') THEN 'YES' 
	WHEN (PROD_NAME = 'Shirt') THEN 'YES' 
	WHEN (PROD_NAME = 'TShirt') THEN 'YES' 
	WHEN (PROD_NAME = 'Atta') THEN 'YES' 
	WHEN (PROD_NAME = 'Lava') THEN 'YES' 
	WHEN (PROD_NAME = 'Biscuit') THEN 'YES' 
	WHEN (PROD_NAME = 'Books') THEN 'YES' 	
	ELSE 'NO'	
END) C_N 
FROM product

SELECT * ,
(CASE 
	WHEN (PROD_ID='1141')THEN 'YES YOU CAN GET Laptop'
	WHEN (PROD_ID='2212')THEN 'WEAR Shirt'
	WHEN (PROD_ID='4524')THEN 'WEAR TShirt'
	WHEN (PROD_ID='4277')THEN 'PATANJALI Atta'
	WHEN (PROD_ID='5252')THEN 'BEST Lava MOBILE'
	WHEN (PROD_ID='241')THEN 'PARLE-G Biscuit'
	WHEN (PROD_ID='123')THEN 'SQL SERVER Books'
	ELSE 'NO'
END) CASE_NO
FROM product

-------------

SELECT * ,
(CASE PROD_ID
	WHEN ('1141')THEN 'YES YOU CAN GET Laptop'
	WHEN ('2212')THEN 'WEAR Shirt'
	WHEN ('4524')THEN 'WEAR TShirt'
	WHEN ('4277')THEN 'PATANJALI Atta'
	WHEN ('5252')THEN 'BEST Lava MOBILE'
	WHEN ('241')THEN 'PARLE-G Biscuit'
	WHEN ('123')THEN 'SQL SERVER Books'
	ELSE 'NO'
END) CASE_NO
FROM product

-----------------------------------------

SELECT SNO, NAME, AGE, COUNTRY, JOINING_DATE, MOBILE_NO, ADDRESS, EMAIL_ID, QUALIFICATION, RELIGION, PROFESSION, SALARY,MEDICAL_INSURANCE,
(
CASE MEDICAL_INSURANCE
	WHEN ('YES') THEN 'NO'
	ELSE 'YES'
END)
C_MI
FROM CUSTOMERS

------------------------------------------------

SELECT SNO, NAME, AGE, COUNTRY, JOINING_DATE, MOBILE_NO, PROFESSION, SALARY,MEDICAL_INSURANCE,
(
CASE 
	WHEN (AGE <= 25) THEN 'FRESHER CUST'
	WHEN (AGE <= 30 AND AGE >= 26) THEN 'MIDDLE CUST'
	WHEN (AGE <= 35 AND AGE >= 31 ) THEN 'AVG CUST'
	WHEN (AGE <= 40 AND AGE >= 36) THEN 'EXPERIENCE CUST'
	ELSE
	'MOST SENIOR'
END
) [EXPERIENCE CUSTOMER]
FROM CUSTOMERS
WHERE
[EXPERIENCE CUSTOMER] = 'FRESHER CUST'
-- An expression of non-boolean type specified in a context where a condition is expected, near 'CUSTOMER'.
-- Invalid column name 'EXPERIENCE CUSTOMER'

SELECT * FROM
(
SELECT SNO, NAME, AGE, COUNTRY, JOINING_DATE, MOBILE_NO, PROFESSION, SALARY,MEDICAL_INSURANCE,
(
CASE 
	WHEN (AGE <= 25) THEN 'FRESHER CUST'
	WHEN (AGE <= 30 AND AGE >= 26) THEN 'MIDDLE CUST'
	WHEN (AGE <= 35 AND AGE >= 31 ) THEN 'AVG CUST'
	WHEN (AGE <= 40 AND AGE >= 36) THEN 'EXPERIENCE CUST'
	ELSE 'MOST SENIOR'	
END
) [EXPERIENCE CUSTOMER]
FROM CUSTOMERS
) TEMP_TBL
WHERE
[EXPERIENCE CUSTOMER] = 'MIDDLE CUST'